### ISSUE TITLE
Fluent bit Kafka Configuration

### ISSUE THREAD

**Issue by AkshayDubey29** [samsung-cnct/fluent-bit-kafka-output-plugin#11]
Hi, We would like to configure the batch size and Kafka buffer parameter in fluent-bit Kafka configuration, Can anyone please help us to configure the same?

[OUTPUT]
Name kafka
Match *
Brokers 192.168.1.3:9092
Topics test

**Comment by davidewatson** [comment]
`fluent-bit` can be built with `kafka` plugin now. Therefore this plugin and repository have been deprecated. Please see the upstream container at https://hub.docker.com/r/fluent/fluent-bit. Using it you should be able to mount an alternative `/fluent-bit/etc/fluent-bit.conf` into the container. Alternatively, there are charts which may be useful: https://github.com/kubernetes/charts/tree/master/stable/fluent-bit
